title: The mysteries of pie
author: natashacmyers
email: natashacmyers@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Pie is essentially the most mysterious thing on the planet. Think schrodinger's cat, ten fold. Nobody knows what's going on inside those pies. 
  What's inside them? Is it even food? Is it even cooked? So many questions. 
  We will discuss in detail throughout this site.

# social links
twitter_username: natashacmyers # DO NOT include the @ character, or else the build will fail!
github_username:  natashacmyers # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
